# Generated by Django 5.1.2 on 2025-08-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgame', '0007_wallet_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('genre', models.CharField(default='Battle Royale', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_images/')),
            ],
        ),
    ]
