# Generated by Django 5.1.2 on 2025-08-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgame', '0009_alter_event_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='old_game',
            field=models.CharField(default='Game', max_length=100),
        ),
    ]
