# Generated by Django 5.1.2 on 2025-08-03 15:14

import mgame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgame', '0011_alter_event_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mgame.models.upload_game_image),
        ),
    ]
