# Generated by Django 5.1.2 on 2025-08-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgame', '0012_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user1ingame',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='user2ingame',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
