# Generated by Django 5.1.2 on 2025-08-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgame', '0013_alter_event_user1ingame_alter_event_user2ingame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
